cabal-version: 3.0
name:          HaskellBasics
version:       0.1.0.0
maintainer:    daniel.kroeni@fhnw.ch
author:        Daniel Kröni
build-type:    Simple

test-suite tests
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.18 && <5,
        hspec ==2.11.17,
        hspec-contrib,
        QuickCheck,
        HUnit
